# To fetch schema from
introspection: http://localhost:5000/graphql/

servers: # same format as for OpenAPI Specification
  - url: https://cx-labs-stg.cisco.com/graphql/
    description: Staging
  - url: https://cx-labs.cisco.com/graphql/
    description: Prod

info: # same format as for OpenAPI Specification
    title: CX Labs API Documentation
    description: |
      CX Labs API is a GraphQL endpoint providing the ability to query and modify all fields and values that
      are provided in our UI. The API is protected by Cisco SSO and is able to be queried using standard OAuth2
      workflows.

      An example script of executing a query against the api can be found [here](https://www.google.com) and an oauth
      client id/secret pair can be generated [here](https://wampmtui.cloudapps.cisco.com/loggedIn#/oauth/clients/0/10/).

domains:
  - name: Asset Automation
    description: |
      Automation is an asynchronous operation that takes two forms. The first is triggering a task,
      these triggers are mutations like [Clear Lines](#operation-clear_lines-post). The second part of the operation
      is fetching the status of the task while it completes with [Task Status](#operation-task_status-post).
    usecases:
      # - name: Task Status
      #   description: QQQ
      #   query: query.task
      - name: Clear Lines # Operation name
        description: QQQ Markdown enabled description for operation # Opearation description
        query: mutation.assetClearLines
        select:
          Task:
            - id
        expand:
          errors:
            - fieldName
            - errorMessage
      - name: Power Commands # Operation name
        description: QQQ Markdown enabled description for operation # Opearation description
        query: mutation.assetPowerActions # Query example - fetching single field
#        select: name # select only specific sub fields. By default - all are selected
#        expand: ports #field3(sub1, sub2, sub3),field4 # go deep by expanding specific fields.
  - name: AAAAA
    description: QQQQQ
#    description: |
#      Automation is an asynchronous operation that takes two forms. The first is triggering a task,
#      these triggers are mutations like #Clear Line. The second part of the operation is fetching the status
#      of the task while it completes.
    usecases:
      - name: BBBBB # Operation name
        description: QQQ Markdown enabled description for operation # Opearation description
        query: query.automatrixDomainGetAllByProviderId # Query example - fetching single field
      - name: CCCCC # Operation name
        description: QQQ Markdown enabled description for operation # Opearation description
        query: query.automatrixDomainGetAllByProviderId # Query example - fetching single field
#        select: name # select only specific sub fields. By default - all are selected
#        expand: ports #field3(sub1, sub2, sub3),field4 # go deep by expanding specific fields.
